@startuml use_case
title Use Case Diagram

actor "Student" as S
actor "System Admin" as SA

rectangle "Authentication Module" {
    usecase "Sign Up" as UC1
    usecase "Log In" as UC2
    }

note right of UC1 : Sign Up is included in Log In

rectangle "Course Management" {
    usecase "View All Courses" as UC3
    usecase "Add Course (Enrollment)" as UC4
    usecase "Update Grade" as UC5
    usecase "Delete Course" as UC6
    }

rectangle "GPA Features" {
    usecase "View GPA" as UC7
    }

S --> UC1
S --> UC2
S --> UC3
S --> UC4
S --> UC5
S --> UC6
S --> UC7

SA --> UC1
SA --> UC2

note right of S: Only authenticated Students can access Course and GPA features
@enduml